(function(root){
 root.createMotionRig=function(THREE,asset){
 const group=new THREE.Group(),bones=[],byId={},rest=[];
 if(asset.rig.vertexJoint.length!==asset.mesh.vertices.length)throw new Error('Binding vertex count mismatch');
 const weights=asset.rig.vertexWeights||asset.rig.vertexJoint.map(j=>[[j,1]]);
 if(weights.length!==asset.mesh.vertices.length)throw new Error('Weight vertex count mismatch');
 weights.forEach(row=>{if(!row.length||row.some(([j,w])=>!Number.isInteger(j)||j<0||j>=asset.rig.joints.length||!Number.isFinite(w)||w<0)||Math.abs(row.reduce((s,p)=>s+p[1],0)-1)>1e-9)throw new Error('Invalid skin weights');});
 asset.rig.joints.forEach(j=>{if(byId[j.id]||(j.parent&&!byId[j.parent]))throw new Error('Invalid joint hierarchy');const b=new THREE.Bone();b.name=j.id;const parent=asset.rig.joints.find(p=>p.id===j.parent);b.position.fromArray(j.pivot);if(parent)b.position.sub(new THREE.Vector3().fromArray(parent.pivot));rest.push(b.position.clone());bones.push(b);byId[j.id]=b;if(j.parent)byId[j.parent].add(b);else group.add(b);});
 group.updateMatrixWorld(true);const inverses=bones.map(b=>b.matrixWorld.clone().invert());
 const apply=()=>{group.updateMatrixWorld(true);const matrices=bones.map((b,i)=>b.matrixWorld.clone().multiply(inverses[i]));const vertices=asset.mesh.vertices.map((p,i)=>{const v=new THREE.Vector3();for(const [j,w]of weights[i])v.addScaledVector(new THREE.Vector3().fromArray(p).applyMatrix4(matrices[j]),w);return v.toArray();});return {vertices,faces:asset.mesh.faces,colors:asset.mesh.colors,joints:bones.map(b=>b.getWorldPosition(new THREE.Vector3()).toArray())};};
 const reset=()=>bones.forEach((b,i)=>{b.rotation.set(0,0,0);b.position.copy(rest[i]);});
 const pose=(clip,time)=>{reset();if(clip)for(const tr of clip.tracks){if(!byId[tr.joint])throw new Error('Unknown animated joint');const keys=tr.keys;let value=keys[keys.length-1][1];for(let i=1;i<keys.length;i++)if(time<=keys[i][0]){const a=keys[i-1],b=keys[i];value=a[1]+(b[1]-a[1])*Math.max(0,(time-a[0])/(b[0]-a[0]));break;}byId[tr.joint].rotation[tr.axis]=value;}return apply();};
 const poseTransforms=(rotations,rootTranslation=[0,0,0])=>{reset();for(const [id,q]of Object.entries(rotations)){if(!byId[id]||q.length!==4||!q.every(Number.isFinite))throw new Error('Invalid quaternion track');byId[id].quaternion.fromArray(q).normalize();}bones[0].position.add(new THREE.Vector3().fromArray(rootTranslation));return apply();};
 const checkedClips=new WeakSet();
 const poseMocap=(clip,time,inPlace=false)=>{if(!checkedClips.has(clip)){if(!Number.isFinite(clip.fps)||clip.fps<=0||!Number.isInteger(clip.frameCount)||clip.frameCount<1||clip.joints.length!==bones.length)throw new Error('Invalid mocap clip');const ids=new Set();for(const tr of clip.joints){if(ids.has(tr.joint)||!byId[tr.joint]||tr.samples.length!==clip.frameCount||tr.samples.some(q=>q.length!==4||!q.every(Number.isFinite)||Math.hypot(...q)<1e-8))throw new Error('Invalid mocap rotation samples');ids.add(tr.joint);}if(clip.rootPosition.samples.length!==clip.frameCount||clip.rootPosition.samples.some(p=>p.length!==3||!p.every(Number.isFinite)))throw new Error('Invalid mocap positions');checkedClips.add(clip);}if(!Number.isFinite(time))throw new Error('Invalid mocap time');const frame=Math.max(0,Math.min(clip.frameCount-1,time*clip.fps)),i=Math.floor(frame),j=Math.min(i+1,clip.frameCount-1),alpha=frame-i;const rotations={};for(const tr of clip.joints){const qa=new THREE.Quaternion().fromArray(tr.samples[i]).normalize(),qb=new THREE.Quaternion().fromArray(tr.samples[j]).normalize();rotations[tr.joint]=qa.slerp(qb,alpha).toArray();}const p=new THREE.Vector3().fromArray(clip.rootPosition.samples[i]).lerp(new THREE.Vector3().fromArray(clip.rootPosition.samples[j]),alpha).sub(new THREE.Vector3().fromArray(clip.rootPosition.pivot));if(inPlace){p.x=0;p.z=0;}return poseTransforms(rotations,p.toArray());};
 return {group,bones,pose,poseTransforms,poseMocap};
 };
})(globalThis);
